/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pos;

import com.mycompany.pos.database.ProductDAO;
import com.mycompany.pos.model.Product;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class InventoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryPanel
     */
    public InventoryPanel() {
        initComponents();
        loadAllProductsToTable();
        
          // Set font and row height
    jTable1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    jTable1.setRowHeight(30);
    
    // Style the table header
        javax.swing.table.JTableHeader header = jTable1.getTableHeader();
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        header.setBackground(new java.awt.Color(44, 88, 110));  // Dark Blue
        header.setForeground(java.awt.Color.WHITE);
        
        header.setReorderingAllowed(false);

    // Set alternate row colors (zebra striping)
jTable1.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {

        java.awt.Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        if (!isSelected) {
            if (row % 2 == 0) {
                cell.setBackground(java.awt.Color.WHITE); // Even rows - white
            } else {
                cell.setBackground(new java.awt.Color(240, 248, 255)); // Odd rows - light blue
            }
        } else {
            cell.setBackground(table.getSelectionBackground()); // Keep selected row color
        }

        return cell;
    }
});

    
    }
private void loadAllProductsToTable() {
    List<Product> products = ProductDAO.getAllProducts();  // Fetch from DB
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear old data

    for (Product p : products) {
        model.addRow(new Object[]{
            p.getId(),
            p.getName(),
            p.getBarcode(),
            p.getCategory(),
            p.getPrice(),
            p.getStock()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        topPanel.setPreferredSize(new java.awt.Dimension(1200, 70));
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.Y_AXIS));

        titlePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 5, 0));
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventory Management");
        titlePanel.add(jLabel1);

        searchPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 10, 0));
        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSearch.setToolTipText("Search by product name or barcode");
        txtSearch.setPreferredSize(new java.awt.Dimension(250, 35));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        searchPanel.add(txtSearch);

        cmbCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Cake", "Pancake", "Drink" }));
        cmbCategory.setToolTipText("Select Category");
        cmbCategory.setPreferredSize(new java.awt.Dimension(150, 35));
        searchPanel.add(cmbCategory);

        btnSearch.setBackground(new java.awt.Color(44, 88, 110));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.setToolTipText("Click to search");
        btnSearch.setBorder(null);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.setPreferredSize(new java.awt.Dimension(100, 35));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        searchPanel.add(btnSearch);

        titlePanel.add(searchPanel);

        topPanel.add(titlePanel);

        add(topPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setBackground(new java.awt.Color(190, 208, 219));
        centerPanel.setPreferredSize(new java.awt.Dimension(1200, 540));
        centerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 400));

        jTable1.setBackground(new java.awt.Color(250, 250, 250));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cake A ", "8964000123456", "Cake", "100", "20"},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Barcode", "Category", "Price", "Stock"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBackground(new java.awt.Color(245, 240, 225));
        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 20));

        btnAdd.setBackground(new java.awt.Color(44, 88, 110));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon("E:\\POS\\resources\\add.png")); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setToolTipText("ToolTip");
        btnAdd.setBorder(null);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdd.setPreferredSize(new java.awt.Dimension(120, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        bottomPanel.add(btnAdd);

        btnEdit.setBackground(new java.awt.Color(44, 88, 110));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon("E:\\POS\\resources\\edit.png")); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("ToolTip");
        btnEdit.setBorder(null);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusPainted(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEdit.setPreferredSize(new java.awt.Dimension(120, 40));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        bottomPanel.add(btnEdit);

        btnDelete.setBackground(new java.awt.Color(44, 88, 110));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon("E:\\POS\\resources\\delete.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("ToolTip");
        btnDelete.setBorder(null);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusPainted(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDelete.setPreferredSize(new java.awt.Dimension(120, 40));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        bottomPanel.add(btnDelete);

        add(bottomPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       AddProductDialog dialog = new AddProductDialog(null, true);
dialog.setVisible(true);

// After dialog closes, reload product list
loadAllProductsToTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText().trim().toLowerCase();
String category = cmbCategory.getSelectedItem().toString();

List<Product> allProducts = ProductDAO.getAllProducts();
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0); // Clear table

for (Product p : allProducts) {
    boolean matchesCategory = category.equals("All") || p.getCategory().equalsIgnoreCase(category);
    boolean matchesSearch = keyword.isEmpty()
            || p.getName().toLowerCase().contains(keyword)
            || p.getBarcode().toLowerCase().contains(keyword);

    if (matchesCategory && matchesSearch) {
        model.addRow(new Object[]{
            p.getId(),
            p.getName(),
            p.getBarcode(),
            p.getCategory(),
            p.getPrice(),
            p.getStock()
        });
    }
}

    }//GEN-LAST:event_btnSearchActionPerformed

   


    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();

if (selectedRow == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please select a product to delete.");
    return;
}

// Get product ID from table
int productId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

// Confirm delete
int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete this product?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION);

if (confirm == javax.swing.JOptionPane.YES_OPTION) {
    boolean success = ProductDAO.deleteProductById(productId);
    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Product deleted successfully.");
        loadAllProductsToTable(); // Refresh table
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete product.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    }//GEN-LAST:event_btnDeleteActionPerformed

   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a product to edit.");
        return;
    }

    // Get data from table
    int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
    String name = jTable1.getValueAt(selectedRow, 1).toString();
    String barcode = jTable1.getValueAt(selectedRow, 2).toString();
    String category = jTable1.getValueAt(selectedRow, 3).toString();
    double price = Double.parseDouble(jTable1.getValueAt(selectedRow, 4).toString());
    int stock = Integer.parseInt(jTable1.getValueAt(selectedRow, 5).toString());

    // Create Product object
    Product product = new Product(id, name, barcode, category, price, stock);

    // Open Edit dialog
    EditProductDialog dialog = new EditProductDialog(null, true, product);
    dialog.setVisible(true);

    // After editing, reload table
    loadAllProductsToTable();
}//GEN-LAST:event_btnEditActionPerformed

	
	

	
	
	
	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
