/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pos;

import com.mycompany.pos.database.SalesDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class POSPanel extends javax.swing.JPanel {
		private double currentTotal = 0.0;
		private double discountedTotal = 0.0;	
    public POSPanel() {
        initComponents();
        initListeners(); // 👈 Add this
		loadProducts();  // 👈 Add this
    }
	
	private String centerText(String text, int width) {
        int padding = (width - text.length()) / 2;
        return " ".repeat(Math.max(0, padding)) + text;
    }
	
	
	
    
   private void updateTotal() {
    double total = 0.0;
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        Object value = model.getValueAt(i, 3); // Amount column
        if (value != null) {
            total += Double.parseDouble(value.toString());
        }
    }

    currentTotal = total;  // ✅ update currentTotal here
    lblTotal.setText("Total: RS " + String.format("%.2f", total));
}


    
    
private void applyDiscount(double percent) {
    double total = 0.0;
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        Object value = model.getValueAt(i, 3); // Amount column
        if (value != null) {
            total += Double.parseDouble(value.toString());
        }
    }

    double discount = total * (percent / 100.0);
    discountedTotal = total - discount;
    lblTotal.setText("Total: RS " + String.format("%.2f", discountedTotal));
}


private void clearTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    double totalAmount = 0.0;
    currentTotal = 0.0;
    discountedTotal = 0.0;
    lblTotal.setText("Total: RS 0.00");
}


private void calculateChange() {
    try {
        double cash = Double.parseDouble(txtCashReceived.getText());
        double totalToUse = discountedTotal > 0 ? discountedTotal : currentTotal;
        double change = cash - totalToUse;

        if (change < 0) change = 0;
        txtChange.setText(String.format("%.2f", change));
    } catch (NumberFormatException e) {
        txtChange.setText("0.00");
    }
}


    
    
    
    private void initListeners() {
    txtCashReceived.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            calculateChange();
        }
    });
}

private void loadProducts() {
    productGridPanel.removeAll(); // Clear previous buttons

    java.util.List<com.mycompany.pos.model.Product> products = com.mycompany.pos.database.ProductDAO.getAllProducts();

    for (com.mycompany.pos.model.Product product : products) {
        javax.swing.JButton btn = new javax.swing.JButton("<html>" + product.getName() + "<br>Rs " + product.getPrice() + "</html>");
        btn.setPreferredSize(new java.awt.Dimension(120, 80));
        btn.setBackground(new java.awt.Color(255, 243, 200));
        btn.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        btn.setForeground(new java.awt.Color(51, 51, 51));

        btn.addActionListener(e -> {
            addToCart(product.getName(), product.getPrice());
        });

        productGridPanel.add(btn);
    }

    productGridPanel.revalidate();
    productGridPanel.repaint();
}


    
    
  

private void addToCart(String itemName, double rate) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    boolean itemFound = false;

    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 0).toString().equals(itemName)) {
            int currentQty = Integer.parseInt(model.getValueAt(i, 1).toString());
            currentQty++;
            double amount = currentQty * rate;

            model.setValueAt(currentQty, i, 1);
            model.setValueAt(amount, i, 3);
            itemFound = true;
            break;
        }
    }

    if (!itemFound) {
        int qty = 1;
        double amount = qty * rate;
        model.addRow(new Object[]{itemName, qty, rate, amount});
    }

    updateTotal();
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        productPanel = new javax.swing.JPanel();
        leftProductPanel = new javax.swing.JPanel();
        subcategoryPanel = new javax.swing.JPanel();
        btnCakes = new javax.swing.JButton();
        btnDrinks = new javax.swing.JButton();
        btnCoffee = new javax.swing.JButton();
        productGridPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        wrapperPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        gapPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn10Off = new javax.swing.JButton();
        btn15Off = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblCashReceivedTitle = new javax.swing.JLabel();
        lblChangeTitle = new javax.swing.JLabel();
        txtCashReceived = new javax.swing.JTextField();
        txtChange = new javax.swing.JTextField();
        btnCheckOut = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 700));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setBackground(new java.awt.Color(190, 208, 219));
        mainPanel.setMaximumSize(new java.awt.Dimension(1200, 700));
        mainPanel.setMinimumSize(new java.awt.Dimension(1200, 700));
        mainPanel.setPreferredSize(new java.awt.Dimension(1200, 700));
        mainPanel.setLayout(new java.awt.BorderLayout());

        productPanel.setBackground(new java.awt.Color(245, 240, 225));
        productPanel.setPreferredSize(new java.awt.Dimension(750, 0));
        productPanel.setLayout(new java.awt.BorderLayout());

        leftProductPanel.setLayout(new java.awt.BorderLayout());

        subcategoryPanel.setBackground(new java.awt.Color(190, 208, 219));
        subcategoryPanel.setPreferredSize(new java.awt.Dimension(0, 80));
        subcategoryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        btnCakes.setBackground(new java.awt.Color(255, 243, 200));
        btnCakes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCakes.setForeground(new java.awt.Color(51, 51, 51));
        btnCakes.setText("Cakes");
        btnCakes.setPreferredSize(new java.awt.Dimension(120, 40));
        subcategoryPanel.add(btnCakes);

        btnDrinks.setBackground(new java.awt.Color(255, 243, 200));
        btnDrinks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDrinks.setForeground(new java.awt.Color(51, 51, 51));
        btnDrinks.setText("Drinks");
        btnDrinks.setPreferredSize(new java.awt.Dimension(120, 40));
        subcategoryPanel.add(btnDrinks);

        btnCoffee.setBackground(new java.awt.Color(255, 243, 200));
        btnCoffee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCoffee.setForeground(new java.awt.Color(51, 51, 51));
        btnCoffee.setText("Coffee");
        btnCoffee.setPreferredSize(new java.awt.Dimension(120, 40));
        subcategoryPanel.add(btnCoffee);

        leftProductPanel.add(subcategoryPanel, java.awt.BorderLayout.NORTH);

        productGridPanel.setBackground(new java.awt.Color(245, 240, 225));
        productGridPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));

        jButton1.setBackground(new java.awt.Color(255, 243, 200));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("<html>Chocolate<br>Cake</html>");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 80));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        productGridPanel.add(jButton1);

        leftProductPanel.add(productGridPanel, java.awt.BorderLayout.CENTER);

        productPanel.add(leftProductPanel, java.awt.BorderLayout.CENTER);

        rightPanel.setBackground(new java.awt.Color(245, 240, 225));
        rightPanel.setPreferredSize(new java.awt.Dimension(400, 0));
        rightPanel.setLayout(new java.awt.BorderLayout());

        wrapperPanel.setLayout(new javax.swing.BoxLayout(wrapperPanel, javax.swing.BoxLayout.Y_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Items", "Qty", "Rate", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        wrapperPanel.add(jScrollPane1);

        gapPanel.setBackground(new java.awt.Color(245, 240, 225));
        gapPanel.setPreferredSize(new java.awt.Dimension(0, 100));
        wrapperPanel.add(gapPanel);

        jPanel1.setMaximumSize(new java.awt.Dimension(390, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(390, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn10Off.setBackground(new java.awt.Color(44, 88, 110));
        btn10Off.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn10Off.setForeground(new java.awt.Color(255, 255, 255));
        btn10Off.setText("10% OFF");
        btn10Off.setPreferredSize(new java.awt.Dimension(120, 40));
        btn10Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10OffActionPerformed(evt);
            }
        });
        jPanel1.add(btn10Off, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn15Off.setBackground(new java.awt.Color(44, 88, 110));
        btn15Off.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn15Off.setForeground(new java.awt.Color(255, 255, 255));
        btn15Off.setText("15% OFF");
        btn15Off.setPreferredSize(new java.awt.Dimension(120, 40));
        btn15Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15OffActionPerformed(evt);
            }
        });
        jPanel1.add(btn15Off, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnClear.setBackground(new java.awt.Color(44, 88, 110));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear ");
        btnClear.setPreferredSize(new java.awt.Dimension(120, 40));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Total: RS 0.00");
        lblTotal.setPreferredSize(new java.awt.Dimension(140, 30));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 50, 280, 30));

        lblCashReceivedTitle.setText("Cash Received");
        lblCashReceivedTitle.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(lblCashReceivedTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblChangeTitle.setText("Change:");
        lblChangeTitle.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(lblChangeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtCashReceived.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(txtCashReceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        txtChange.setEditable(false);
        txtChange.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        btnCheckOut.setBackground(new java.awt.Color(44, 88, 110));
        btnCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckOut.setText("Check Out");
        btnCheckOut.setPreferredSize(new java.awt.Dimension(360, 50));
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        wrapperPanel.add(jPanel1);

        rightPanel.add(wrapperPanel, java.awt.BorderLayout.CENTER);

        productPanel.add(rightPanel, java.awt.BorderLayout.EAST);

        mainPanel.add(productPanel, java.awt.BorderLayout.CENTER);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    

    // ✅ Call the addToCart method to actually add item to the table
    addToCart("Chocolate Cake", 200.0);
}
                

               

    private void btn10OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10OffActionPerformed
             applyDiscount(10); // 10% discount
    }//GEN-LAST:event_btn10OffActionPerformed

    private void btn15OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15OffActionPerformed
     
        applyDiscount(15); // 15% discount     
    }//GEN-LAST:event_btn15OffActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       clearTable();
    }//GEN-LAST:event_btnClearActionPerformed

	private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    if (model.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cart is empty!");
        return;
    }

    

    StringBuilder receipt = new StringBuilder();
    // Header
		receipt.append(centerText("★ THE BAKERY SHOP ★", 42)).append("\n");
		receipt.append(centerText("404 Location Not Found", 32) + "\n");
		receipt.append(centerText("Our phone melted in the oven.", 32) + "\n");

		
		// Date & time
java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
String now = java.time.LocalDateTime.now().format(dtf);
receipt.append("Date: ").append(now).append("\n");
receipt.append("=".repeat(32) + "\n");


	
// Table header
receipt.append(String.format("%-14s %3s %6s %7s\n", "Item", "Qty", "Rate", "Total"));

receipt.append("--------------------------------\n");
		
		

    for (int i = 0; i < model.getRowCount(); i++) {
        String itemName = model.getValueAt(i, 0).toString();
        int qty = Integer.parseInt(model.getValueAt(i, 1).toString());
        double rate = Double.parseDouble(model.getValueAt(i, 2).toString());
        double amount = Double.parseDouble(model.getValueAt(i, 3).toString());

        receipt.append(String.format("%-12s %2d %6.2f %7.2f\n", itemName, qty, rate, amount));


        SalesDAO.insertSale(itemName, qty, rate, amount);
    }

    // Totals
receipt.append("--------------------------------\n");
String totalText = lblTotal.getText().replace("Total: RS", "").trim();
String cashText = txtCashReceived.getText().trim();
String changeText = txtChange.getText().trim();
receipt.append("\n");
receipt.append(String.format("%-25s %6s\n", "*** TOTAL ***", totalText.toUpperCase()));
receipt.append(String.format("%-25s %6s\n", "*** CASH  ***", (cashText.isEmpty() ? "0.00" : cashText).toUpperCase()));
receipt.append(String.format("%-25s %6s\n", "*** CHANGE ***", (changeText.isEmpty() ? "0.00" : changeText).toUpperCase()));
receipt.append("--------------------------------\n");
receipt.append(centerText("Thank you for your visit!", 32) + "\n");
receipt.append(centerText("Created by @_wajih_ullah 📸", 32) + "\n");



    // Show in PrintWindow
    PrintWindow pw = new PrintWindow(receipt.toString());
    pw.setVisible(true);

    // Clear cart and reset fields
    clearTable();
    txtCashReceived.setText("");
    txtChange.setText("");
}


    
        
                                               


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10Off;
    private javax.swing.JButton btn15Off;
    private javax.swing.JButton btnCakes;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCoffee;
    private javax.swing.JButton btnDrinks;
    private javax.swing.JPanel gapPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCashReceivedTitle;
    private javax.swing.JLabel lblChangeTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel leftProductPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel productGridPanel;
    private javax.swing.JPanel productPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel subcategoryPanel;
    private javax.swing.JTextField txtCashReceived;
    private javax.swing.JTextField txtChange;
    private javax.swing.JPanel wrapperPanel;
    // End of variables declaration//GEN-END:variables

}