/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pos;

/**
 *
 * @author HP
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
        mainContentPanel.setPreferredSize(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContentPanel = new javax.swing.JPanel();
        dateFilterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        dateEnd = new com.toedter.calendar.JDateChooser();
        btnGenerateReport = new javax.swing.JButton();
        scrollPaneReports = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        summaryPanel = new javax.swing.JPanel();
        lblTotalInvoices = new javax.swing.JLabel();
        lblInvoiceCount = new javax.swing.JLabel();
        lblTotalItems = new javax.swing.JLabel();
        lblItemCount = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        lblSalesAmount = new javax.swing.JLabel();

        mainContentPanel.setBackground(new java.awt.Color(190, 208, 219));
        mainContentPanel.setPreferredSize(new java.awt.Dimension(1280, 820));
        mainContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateFilterPanel.setBackground(new java.awt.Color(230, 230, 230));
        dateFilterPanel.setPreferredSize(new java.awt.Dimension(1240, 60));
        dateFilterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 88, 110));
        jLabel1.setText("Select Date Range:");
        dateFilterPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        dateStart.setPreferredSize(new java.awt.Dimension(150, 25));
        dateFilterPanel.add(dateStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 17, -1, -1));

        dateEnd.setPreferredSize(new java.awt.Dimension(150, 25));
        dateFilterPanel.add(dateEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 17, -1, -1));

        btnGenerateReport.setBackground(new java.awt.Color(44, 88, 110));
        btnGenerateReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerateReport.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.setPreferredSize(new java.awt.Dimension(160, 30));
        dateFilterPanel.add(btnGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 15, -1, -1));

        mainContentPanel.add(dateFilterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        scrollPaneReports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 88, 110), 3));
        scrollPaneReports.setPreferredSize(new java.awt.Dimension(1280, 590));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10-05-2025", "3287123", "05", "10000"},
                {"11-05-2025", "1237213", "06", "20000"},
                {"12-05-2025", "2487241", "07", "30000"},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Invoice No.", "Item Count", "Total Amount"
            }
        ));
        scrollPaneReports.setViewportView(jTable1);

        mainContentPanel.add(scrollPaneReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        summaryPanel.setBackground(new java.awt.Color(208, 208, 208));
        summaryPanel.setPreferredSize(new java.awt.Dimension(1240, 120));
        summaryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalInvoices.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalInvoices.setForeground(new java.awt.Color(28, 28, 28));
        lblTotalInvoices.setText("Total Invoices:");
        summaryPanel.add(lblTotalInvoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblInvoiceCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInvoiceCount.setForeground(new java.awt.Color(28, 28, 28));
        lblInvoiceCount.setText("3");
        summaryPanel.add(lblInvoiceCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        lblTotalItems.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalItems.setForeground(new java.awt.Color(28, 28, 28));
        lblTotalItems.setText("Total Items:");
        summaryPanel.add(lblTotalItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        lblItemCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblItemCount.setForeground(new java.awt.Color(28, 28, 28));
        lblItemCount.setText("18");
        summaryPanel.add(lblItemCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        lblTotalSales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalSales.setForeground(new java.awt.Color(28, 28, 28));
        lblTotalSales.setText("Total Sales:");
        summaryPanel.add(lblTotalSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        lblSalesAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSalesAmount.setForeground(new java.awt.Color(28, 28, 28));
        lblSalesAmount.setText("Rs. 60,000");
        summaryPanel.add(lblSalesAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        mainContentPanel.add(summaryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReport;
    private com.toedter.calendar.JDateChooser dateEnd;
    private javax.swing.JPanel dateFilterPanel;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInvoiceCount;
    private javax.swing.JLabel lblItemCount;
    private javax.swing.JLabel lblSalesAmount;
    private javax.swing.JLabel lblTotalInvoices;
    private javax.swing.JLabel lblTotalItems;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JScrollPane scrollPaneReports;
    private javax.swing.JPanel summaryPanel;
    // End of variables declaration//GEN-END:variables
}
